create extension if not exists pgcrypto;

create table if not exists public.portfolios (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 160),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_members (
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('owner', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (portfolio_id, user_id)
);

create table if not exists public.imports (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  uploaded_by uuid not null references auth.users(id) on delete restrict,
  source_type text not null check (source_type in ('budget', 'actual')),
  original_filename text not null,
  storage_path text,
  row_count integer not null default 0 check (row_count >= 0),
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  error_message text,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create unique index if not exists imports_one_active_type_idx on public.imports (portfolio_id, source_type) where is_active;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  project_code text not null,
  project_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (portfolio_id, project_code)
);

create table if not exists public.budget_lines (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  import_id uuid not null references public.imports(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete restrict,
  month_label text not null,
  budget_item text not null,
  amount numeric(20, 2) not null,
  source_row integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.actual_lines (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  import_id uuid not null references public.imports(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete restrict,
  month_label text not null,
  actual_item text not null,
  amount numeric(20, 2) not null,
  source_row integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Consulta de portafolio',
  created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  model text,
  created_at timestamptz not null default now()
);

create table if not exists public.analysis_runs (
  id uuid primary key default gen_random_uuid(),
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict,
  analysis_type text not null check (analysis_type in ('portfolio_summary', 'chat_query', 'import_validation')),
  budget_import_id uuid references public.imports(id) on delete set null,
  actual_import_id uuid references public.imports(id) on delete set null,
  session_id uuid references public.chat_sessions(id) on delete set null,
  question text,
  answer text,
  model text,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists imports_portfolio_type_idx on public.imports (portfolio_id, source_type, created_at desc);
create index if not exists projects_portfolio_idx on public.projects (portfolio_id, project_code);
create index if not exists budget_lines_portfolio_import_idx on public.budget_lines (portfolio_id, import_id, project_id);
create index if not exists actual_lines_portfolio_import_idx on public.actual_lines (portfolio_id, import_id, project_id);
create index if not exists budget_lines_month_idx on public.budget_lines (portfolio_id, month_label);
create index if not exists actual_lines_month_idx on public.actual_lines (portfolio_id, month_label);
create index if not exists chat_sessions_portfolio_idx on public.chat_sessions (portfolio_id, created_at desc);
create index if not exists chat_messages_session_idx on public.chat_messages (session_id, created_at);
create index if not exists analysis_runs_portfolio_idx on public.analysis_runs (portfolio_id, created_at desc);

create or replace function public.has_portfolio_access(target_portfolio_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.portfolios p
    where p.id = target_portfolio_id and p.owner_id = (select auth.uid())
  ) or exists (
    select 1 from public.portfolio_members pm
    where pm.portfolio_id = target_portfolio_id and pm.user_id = (select auth.uid())
  );
$$;

create or replace view public.project_execution_summary
with (security_invoker = true)
as
select
  p.portfolio_id,
  p.id as project_id,
  p.project_code,
  p.project_name,
  coalesce(b.budgeted_amount, 0)::numeric as budgeted_amount,
  coalesce(a.actual_amount, 0)::numeric as actual_amount,
  (coalesce(b.budgeted_amount, 0) - coalesce(a.actual_amount, 0))::numeric as variance,
  case when coalesce(b.budgeted_amount, 0) = 0 then 0
       else round((coalesce(a.actual_amount, 0) / b.budgeted_amount * 100)::numeric, 2)
  end as execution_percent
from public.projects p
left join (
  select bl.project_id, sum(bl.amount) as budgeted_amount
  from public.budget_lines bl
  join public.imports i on i.id = bl.import_id and i.is_active = true and i.source_type = 'budget'
  group by bl.project_id
) b on b.project_id = p.id
left join (
  select al.project_id, sum(al.amount) as actual_amount
  from public.actual_lines al
  join public.imports i on i.id = al.import_id and i.is_active = true and i.source_type = 'actual'
  group by al.project_id
) a on a.project_id = p.id;

alter table public.portfolios enable row level security;
alter table public.portfolio_members enable row level security;
alter table public.imports enable row level security;
alter table public.projects enable row level security;
alter table public.budget_lines enable row level security;
alter table public.actual_lines enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.analysis_runs enable row level security;

create policy "portfolio owners and members can read portfolios" on public.portfolios for select to authenticated using (owner_id = (select auth.uid()) or exists (select 1 from public.portfolio_members pm where pm.portfolio_id = id and pm.user_id = (select auth.uid())));
create policy "users can create portfolios" on public.portfolios for insert to authenticated with check (owner_id = (select auth.uid()));
create policy "portfolio owners can update portfolios" on public.portfolios for update to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "portfolio owners can delete portfolios" on public.portfolios for delete to authenticated using (owner_id = (select auth.uid()));

create policy "users can read own membership" on public.portfolio_members for select to authenticated using (user_id = (select auth.uid()));
create policy "owners can add membership" on public.portfolio_members for insert to authenticated with check (exists (select 1 from public.portfolios p where p.id = portfolio_id and p.owner_id = (select auth.uid())));
create policy "owners can update membership" on public.portfolio_members for update to authenticated using (exists (select 1 from public.portfolios p where p.id = portfolio_id and p.owner_id = (select auth.uid()))) with check (exists (select 1 from public.portfolios p where p.id = portfolio_id and p.owner_id = (select auth.uid())));
create policy "owners can remove membership" on public.portfolio_members for delete to authenticated using (exists (select 1 from public.portfolios p where p.id = portfolio_id and p.owner_id = (select auth.uid())));

create policy "members can read imports" on public.imports for select to authenticated using (public.has_portfolio_access(portfolio_id));
create policy "members can create imports" on public.imports for insert to authenticated with check (public.has_portfolio_access(portfolio_id) and uploaded_by = (select auth.uid()));
create policy "members can update imports" on public.imports for update to authenticated using (public.has_portfolio_access(portfolio_id)) with check (public.has_portfolio_access(portfolio_id));

create policy "members can read projects" on public.projects for select to authenticated using (public.has_portfolio_access(portfolio_id));
create policy "members can create projects" on public.projects for insert to authenticated with check (public.has_portfolio_access(portfolio_id));
create policy "members can update projects" on public.projects for update to authenticated using (public.has_portfolio_access(portfolio_id)) with check (public.has_portfolio_access(portfolio_id));

create policy "members can read budget lines" on public.budget_lines for select to authenticated using (public.has_portfolio_access(portfolio_id));
create policy "members can create budget lines" on public.budget_lines for insert to authenticated with check (public.has_portfolio_access(portfolio_id));
create policy "members can read actual lines" on public.actual_lines for select to authenticated using (public.has_portfolio_access(portfolio_id));
create policy "members can create actual lines" on public.actual_lines for insert to authenticated with check (public.has_portfolio_access(portfolio_id));

create policy "users can read chat sessions" on public.chat_sessions for select to authenticated using (user_id = (select auth.uid()) and public.has_portfolio_access(portfolio_id));
create policy "users can create chat sessions" on public.chat_sessions for insert to authenticated with check (user_id = (select auth.uid()) and public.has_portfolio_access(portfolio_id));
create policy "users can read chat messages" on public.chat_messages for select to authenticated using (user_id = (select auth.uid()) and public.has_portfolio_access(portfolio_id));
create policy "users can create chat messages" on public.chat_messages for insert to authenticated with check (user_id = (select auth.uid()) and public.has_portfolio_access(portfolio_id));

create policy "members can read analysis runs" on public.analysis_runs for select to authenticated using (public.has_portfolio_access(portfolio_id));
create policy "members can create analysis runs" on public.analysis_runs for insert to authenticated with check (created_by = (select auth.uid()) and public.has_portfolio_access(portfolio_id));

insert into storage.buckets (id, name, public) values ('portfolio-files', 'portfolio-files', false) on conflict (id) do nothing;
create policy "users can upload own portfolio files" on storage.objects for insert to authenticated with check (bucket_id = 'portfolio-files' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "users can read own portfolio files" on storage.objects for select to authenticated using (bucket_id = 'portfolio-files' and (storage.foldername(name))[1] = (select auth.uid())::text);

grant execute on function public.has_portfolio_access(uuid) to authenticated;
grant select on public.project_execution_summary to authenticated;
grant select, insert, update, delete on public.portfolios, public.portfolio_members, public.imports, public.projects, public.budget_lines, public.actual_lines, public.chat_sessions, public.chat_messages, public.analysis_runs to authenticated;
grant usage, select on all sequences in schema public to authenticated;
